version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: dmvelt-backend
    depends_on:
      - db
    volumes:
      - ./shared:/app/shared
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dmvelt
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: dmvelt-frontend
    depends_on:
      - backend
    volumes:
      - ./shared:/app/shared
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lienmanager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
