import "../styles/globals.css";
import { AuthProvider } from "./context/AuthContext";
import GoogleMapsLoader from "components/GoogleMapsLoader";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <GoogleMapsLoader />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
