name: Deploy to App Runner
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials via IDC
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Deploy frontend container to App Runner
      - name: Deploy frontend to App Runner
        id: deploy-frontend
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: my-frontend-app
          image-repository: ${{ secrets.AWS_ECR_FRONT_REPO }}
          image-tag: latest

      # Step 4: Deploy backend container to App Runner
      - name: Deploy backend to App Runner
        id: deploy-backend
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: my-backend-app
          image-repository: ${{ secrets.AWS_ECR_BACK_REPO }}
          image-tag: latest

      - name: URLs
        run: |
          echo "Frontend 👉 ${{ steps.deploy-frontend.outputs.service-url }}"
          echo "Backend  👉 ${{ steps.deploy-backend.outputs.service-url }}"
