name: Deploy to App Runner
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      BACKEND_IMAGE: my-backend-app
      FRONTEND_IMAGE: my-frontend-app

    steps:
      # Step 1: Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 2: Configure AWS credentials via IDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

      - name: Build backend image
        run: |
          docker build -t $BACKEND_IMAGE -f ./backend/Dockerfile .
          docker tag $BACKEND_IMAGE:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$BACKEND_IMAGE:latest
          docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$BACKEND_IMAGE:latest

      - name: Build frontend image
        run: |
          docker build -t $FRONTEND_IMAGE -f ./frontend/Dockerfile .
          docker tag $FRONTEND_IMAGE:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$FRONTEND_IMAGE:latest
          docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$FRONTEND_IMAGE:latest

      # Step 3: Deploy frontend container to App Runner
      - name: Deploy frontend to App Runner
        id: deploy-frontend
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: my-frontend-app
          image-repository: ${{ secrets.AWS_ECR_FRONT_REPO }}
          image-tag: latest

      # Step 4: Deploy backend container to App Runner
      - name: Deploy backend to App Runner
        id: deploy-backend
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: my-backend-app
          image-repository: ${{ secrets.AWS_ECR_BACK_REPO }}
          image-tag: latest

      - name: URLs
        run: |
          echo "Frontend 👉 ${{ steps.deploy-frontend.outputs.service-url }}"
          echo "Backend  👉 ${{ steps.deploy-backend.outputs.service-url }}"
