name: Deploy to App Runner
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy frontend to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: my-frontend-app
          image-repository: ${{ secrets.AWS_ECR_FRONT_REPO }}
          image-tag: latest
      - name: Deploy backend to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: my-backend-app
          image-repository: ${{ secrets.AWS_ECR_BACK_REPO }}
          image-tag: latest

      - name: URLs
        run: |
          echo "Frontend 👉 ${{ steps.deploy-frontend.outputs.service-url }}"
          echo "Backend  👉 ${{ steps.deploy-backend.outputs.service-url }}"
